---

name: zizmor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  zizmor:
    runs-on: ubuntu-latest
    name: zizmor
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Install zizmor
        run: pipx install zizmor==1.24.1

      - name: Run zizmor
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: zizmor --min-severity=medium .github/workflows/
